#############################################################################
# Makefile for building: cvtutf8
# Generated by qmake (2.01a) (Qt 4.8.2) on: Mon Apr 21 15:08:14 2014
# Project:  cvtutf8.pro
# Template: app
# Command: /opt/iOne/Qt_4.8.2/bin/qmake -o Makefile cvtutf8.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -std=c++0x -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/iOne/Qt_4.8.2-20140318/mkspecs/qws/linux-arm-gnueabi-g++ -I. -I/opt/iOne/Qt_4.8.2-20140318/include/QtCore -I/opt/iOne/Qt_4.8.2-20140318/include/QtNetwork -I/opt/iOne/Qt_4.8.2-20140318/include -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/iOne/Qt_4.8.2/lib
LIBS          = $(SUBLIBS)  -L/opt/iOne/Qt_4.8.2/lib -lxlsreader -liconv -lm -lQtNetwork -L/opt/iOne/Qt_4.8.2/lib -lQtCore -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/iOne/Qt_4.8.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		getFileStringUnicode.cpp \
		xlsHandler.cpp 
OBJECTS       = main.o \
		getFileStringUnicode.o \
		xlsHandler.o
DIST          = /opt/iOne/Qt_4.8.2-20140318/mkspecs/common/unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/linux.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base-unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-base.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/qws.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/qconfig.pri \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_functions.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_config.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/exclusive_builds.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_pre.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/release.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_post.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/warn_on.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/unix/thread.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/moc.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/resources.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/uic.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/yacc.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/lex.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/include_source_dir.prf \
		cvtutf8.pro
QMAKE_TARGET  = cvtutf8
DESTDIR       = 
TARGET        = cvtutf8

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cvtutf8.pro  /opt/iOne/Qt_4.8.2-20140318/mkspecs/qws/linux-arm-gnueabi-g++/qmake.conf /opt/iOne/Qt_4.8.2-20140318/mkspecs/common/unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/linux.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base-unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-base.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-unix.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/qws.conf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/qconfig.pri \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_functions.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_config.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/exclusive_builds.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_pre.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/release.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_post.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/warn_on.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/unix/thread.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/moc.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/resources.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/uic.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/yacc.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/lex.prf \
		/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/include_source_dir.prf \
		/opt/iOne/Qt_4.8.2/lib/libQtNetwork.prl \
		/opt/iOne/Qt_4.8.2/lib/libQtCore.prl
	$(QMAKE) -o Makefile cvtutf8.pro
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/unix.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/linux.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/gcc-base-unix.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-base.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/g++-unix.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/common/qws.conf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/qconfig.pri:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_functions.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt_config.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/exclusive_builds.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_pre.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/release.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/default_post.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/warn_on.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/qt.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/unix/thread.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/moc.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/resources.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/uic.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/yacc.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/lex.prf:
/opt/iOne/Qt_4.8.2-20140318/mkspecs/features/include_source_dir.prf:
/opt/iOne/Qt_4.8.2/lib/libQtNetwork.prl:
/opt/iOne/Qt_4.8.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile cvtutf8.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cvtutf81.0.0 || $(MKDIR) .tmp/cvtutf81.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cvtutf81.0.0/ && $(COPY_FILE) --parents getFileStringUnicode.h xlsHandler.h .tmp/cvtutf81.0.0/ && $(COPY_FILE) --parents main.cpp getFileStringUnicode.cpp xlsHandler.cpp .tmp/cvtutf81.0.0/ && (cd `dirname .tmp/cvtutf81.0.0` && $(TAR) cvtutf81.0.0.tar cvtutf81.0.0 && $(COMPRESS) cvtutf81.0.0.tar) && $(MOVE) `dirname .tmp/cvtutf81.0.0`/cvtutf81.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cvtutf81.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp xlsHandler.h \
		getFileStringUnicode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

getFileStringUnicode.o: getFileStringUnicode.cpp getFileStringUnicode.h \
		xlsHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o getFileStringUnicode.o getFileStringUnicode.cpp

xlsHandler.o: xlsHandler.cpp xlsHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xlsHandler.o xlsHandler.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

